// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RPI_API.Data;

#nullable disable

namespace RPI_API.Migrations
{
    [DbContext(typeof(DisplayContext))]
    [Migration("20250909182137_AddDisplayUrlToImageData")]
    partial class AddDisplayUrlToImageData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("RPI_API.Models.DisplayData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brightness")
                        .HasColumnType("TEXT");

                    b.Property<string>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("StopTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DisplayData");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brightness = "100",
                            StartTime = "08:00",
                            StopTime = "20:00",
                            UpdatedAt = new DateTime(2025, 4, 6, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("RPI_API.Models.ImageData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ImageData");
                });

            modelBuilder.Entity("RPI_API.Models.WeatherDisplayData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Temperature")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WeatherCode")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WeatherDisplayData");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Temperature = "72°F",
                            Text = "",
                            UpdatedAt = new DateTime(2025, 4, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            WeatherCode = "3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
