// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RPI_API.Data;

#nullable disable

namespace RPI_API.Migrations
{
    [DbContext(typeof(WeatherDisplayContext))]
    [Migration("20250406231030_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("RPI_API.Models.WeatherDisplayData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("StopTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Temperature")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WeatherCode")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WeatherDisplayData");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            StartTime = "08:00",
                            StopTime = "18:00",
                            Temperature = "72°F",
                            Text = "",
                            UpdatedAt = new DateTime(2025, 4, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            WeatherCode = "3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
